@startuml Library System
entity "BookCopy" {
    +copy_id : integer
    +ISBN : string
    shelf_location : string
    --
    PK (copy_id, ISBN)
    FK (ISBN) references Book
}

entity "Book" {
    +ISBN : string <<PK>>
    publication_year : integer
    title : string
    author : string
    page_count : integer
    publisher_id : integer <<FK>>
}

entity "Publisher" {
    +publisher_id : integer <<PK>>
    name : string
    address : string
}

entity "Category" {
    +category_id : integer <<PK>>
    name : string
    parent_category_id : integer <<FK>>
}

entity "Reader" {
    +reader_id : integer <<PK>>
    last_name : string
    first_name : string
    address : string
    birth_date : date
}

entity "Loan" {
    +loan_id : integer <<PK>>
    reader_id : integer <<FK>>
    copy_id : integer <<FK>>
    ISBN : string <<FK>>
    checkout_date : date
    due_date : date
    return_date : date
}

entity "Book_Category" {
    +ISBN : string <<PK, FK>>
    +category_id : integer <<PK, FK>>
}

Book ||--o{ BookCopy: "has"
Book ||--|| Publisher: "published by"
Book ||--o{ Book_Category: "has"
Category ||--o{ Book_Category: "belongs to"
Category ||--o{ Category : "is subcategory of"
Reader ||--o{ Loan : "borrows"
BookCopy ||--o{ Loan : "is borrowed in"
@enduml