@startuml Library System
entity "BookCopy" {
    +copy_id : integer <<PK>>
    shelf_location : string
    ISBN : string <<FK>>
}

entity "Book" {
    +ISBN : string <<PK>>
    publication_year : integer
    title : string
    author : string
    page_count : integer
}

entity "Publisher" {
    +publisher_id : integer <<PK>>
    name : string
    address : string
}

entity "Category" {
    +category_id : integer <<PK>>
    name : string
    parent_category_id : integer <<FK>>
}

entity "Reader" {
    +reader_id : integer <<PK>>
    last_name : string
    first_name : string
    address : string
    birth_date : date
}

entity "Record" {
    +loan_id : integer <<PK>>
    reader_id : integer <<FK>>
    copy_id : integer <<FK>>
    checkout_date : date
    due_date : date
}

Book ||--o{ BookCopy: "has"
Book }o--o{ Publisher: "published by"
Book }o--o{ Category: "belongs to"
Category ||--o{ Category : "is subcategory of"
Reader ||--o{ Record : "borrows"
BookCopy ||--o{ Record : "is borrowed in"
@enduml