@startuml Railway System

' Entities
class Station {
  +Name : String <<PK>>
  +Tracks : Integer
}

class City {
  +Name : String <<PK>>
  +Region : String
}

class Train {
  +TrainNr : Integer <<PK>>
  +Length : Integer
}

' Relationships
class Connected {
  +StationName : String <<PK, FK>>
  +TrainNr : Integer <<PK, FK>>
  +Departure : Time
  +Arrival : Time
}

class Start {
  +StationName : String <<PK, FK>>
  +TrainNr : Integer <<PK, FK>>
}

class End {
  +StationName : String <<PK, FK>>
  +TrainNr : Integer <<PK, FK>>
}

' Relationships
City "1" -- "N" Station : Lie_in >
Station "1" -- "N" Connected
Station "1" -- "N" Start
Station "1" -- "N" End
Train "1" -- "N" Connected
Train "1" -- "N" Start
Train "1" -- "N" End

@enduml