@startuml Hospital

class Patient {
    +PatientNr : Integer <<PK>>
    Name : String
    Disease : String
}

class Room {
    +RoomNr : Integer <<PK>>
    +StatNr : Integer <<FK>>
    Beds : Integer
}

class Station {
    +StatNr : Integer <<PK>>
    Name : String
}

class StationPersonnel {
    +PersNr : Integer <<PK>>
    +StatNr : Integer <<FK>>
    Name : String
}

class Caregiver {
    +PersNr : Integer <<PK, FK>>
    Qualification : String
}

class Doctor {
    +PersNr : Integer <<PK, FK>>
    Area : String
    Rank : String
}

class Admission {
    +AdmissionId : Integer <<PK>>
    +PatientNr : Integer <<FK>>
    +RoomNr : Integer <<FK>>
    from : Date
    to : Date
}

class Treatment {
    +TreatmentId : Integer <<PK>>
    +PatientNr : Integer <<FK>>
    +DoctorPersNr : Integer <<FK>>
}

Patient "1" -- "N" Admission : "is admitted in"
Room "1" -- "N" Admission : "hosts"
Station "1" -- "N" Room : "has"
Station "1" -- "N" StationPersonnel : "employs"
StationPersonnel <|-- Caregiver : "is a"
StationPersonnel <|-- Doctor : "is a"
Doctor "1" -- "N" Treatment : "performs"
Patient "1" -- "N" Treatment : "receives"

@enduml