services:
  lib:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "lib"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./lib_data:/var/lib/postgresql/data
      - ./lib.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5437:5432"
  train:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "train"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./train_data:/var/lib/postgresql/data
      - ./train/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5438:5432"