@startuml Location and Relationships
entity "Apartment" {

}

entity "House" {
}

entity "Street" {

}

entity "City" {

}

entity "Country" {

}

entity "Team" {
  team_id
}

entity "Referee" {
    referee_id
}

entity "Match" {
  match_id
  team1_id
  team2_id
  referee_id
}

entity Male {
}

entity Female {
}

Apartment }o--|| House
House }o--|| Street
Street }o--|| City
City }o--|| Country

Match }o--|| Team : home_team
Match }o--|| Team : away_team
Match }o--|| Referee

Male }o--|| Male : is son of
Male }o--|| Female : is son of
Female }o--|| Male : is daughter of
Female }o--|| Female : is daughter of

@enduml
